-- MySQL Script generated by MySQL Workbench
-- Tue Nov 28 10:40:15 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Aluno`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Aluno` ;

CREATE TABLE Aluno  (
  `idAluno` INT NOT NULL,
  `Nome` VARCHAR(100) NULL,
  PRIMARY KEY (`idAluno`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sala`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Sala` ;

CREATE TABLE Sala (
  `idSala` INT NOT NULL,
  `Escola` VARCHAR(45) NULL,
  `Hora` INT NULL,
  PRIMARY KEY (`idSala`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Nota`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Nota` ;

CREATE TABLE Nota (
  `Aluno_idAluno` INT NOT NULL,
  `N1` FLOAT NULL,
  `N2` FLOAT NULL,
  `Media` FLOAT NULL,
  `Sala_idSala` INT NOT NULL,
  PRIMARY KEY (`Aluno_idAluno`,`Sala_idSala`),
  INDEX `fk_Aluno_has_Sala_Aluno1_idx` (`Aluno_idAluno` ASC),
  INDEX `fk_Aluno_has_Sala_Sala1_idx` (`Sala_idSala` ASC),
  CONSTRAINT `fk_Aluno_has_Sala_Aluno1`
    FOREIGN KEY (`Aluno_idAluno`)
    REFERENCES `Aluno` (`idAluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Aluno_has_Sala_Sala1`
    FOREIGN KEY (`Sala_idSala`)
    REFERENCES `Sala` (`idSala`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
